name: 02-workflow-events

on: 
    pull_request:
      branches:
        - main
    workflow_dispatch: {}
    schedule:
      - cron: '30 20 * * *' 


jobs:
    echo:
        runs-on: github-action-labs
        steps:
          - name: Show the trigger
            run: echo "Triggered by $GITHUB_EVENT_NAME"