name: 06 - Contexts

on:
    workflow_dispatch:
        inputs:
            debug:
                description: 'Enable debug mode'
                type: boolean
                required: true
                default: false
            select:
                type: choice
                options:
                    - 1
                    - 2
                    - 3
                default: '1'


env:
    MY_ENV: 'Workflow'

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_ENV: 'Job'
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow}} Run ID: ${{ github.run_id }} Run number: ${{ github.run_number }}"
            - name: Retrieve Variable
              env:
                MY_ENV: 'Step'
              run: |
                echo "My Variable: ${{ vars.MY_VAR }}"
                echo "My Env: ${{ env.MY_ENV }}"
                echo "My Secret: ${{ secrets.PASSWORD }}"
