name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure


jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.step1.outputs.Status }}
        steps:
            - name: 'Build'
              id: step1
              run: echo "Status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: 'Deploy'
              run: echo ${{ needs.build.outputs.build-status }}
