name: from json workflow

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: PROD
        steps:
            - name: echo
              if: fromJSON(vars.PROD_VAR) == false
              run: exit 1

    status-check:
        runs-on: ubuntu-latest
        if: failure()
        steps:
            - name: status-check
              run: echo "Got exit 1 status"
